language: node_js
node_js:
  - 9

jobs:
  include:
    - stage: Audit
      install: npm install -g npm-audit-resolver
      script:
        - check-audit --json


    # - stage: Unit Tests
    #   script: npm run test

    # - stage: Build Application
    #   script:
    #     - docker build --tag app-nodejs .
