language: node_js
node_js:
  - 9

jobs:
  include:
    - stage: Audit
      install:
        - npm install --save-exact lodash@4.0.0
        - npm install --save node-os-utils
      script:
        - npm run audit


    # - stage: Unit Tests
    #   script: npm run test

    # - stage: Build Application
    #   script:
    #     - docker build --tag app-nodejs .
