language: node_js
node_js:
  - 11
cache:
  directories:
    - ~/.npm
jobs:
  include:
    - stage: Audit
      install: npm install -g npm-audit-ci
      script:
        - npm-audit-ci
        - npm audit

    - stage: Lint Checking
      script: npm run lint

    - stage: Unit Tests
      script:
        - npm run travis_start
        - npm run test

    - stage: Build Application
      script:
        - docker build --tag app-nodejs .
