language: node_js
node_js:
  - 11

jobs:
  include:
    - stage: Audit
      install: npm install -g npm-audit-ci
      script:
        - npm-audit-ci


    # - stage: Unit Tests
    #   script: npm run test

    # - stage: Build Application
    #   script:
    #     - docker build --tag app-nodejs .
