language: node_js
node_js:
  - 9

jobs:
  include:
    - stage: Lint
      script:
        - audit-ci --moderate
        - npm run lint

    # - stage: Unit Tests
    #   script: npm run test

    # - stage: Build Application
    #   script:
    #     - docker build --tag app-nodejs .
