language: node_js
node_js:
  - 9

jobs:
  include:
    - stage: Audit
      script:
        - npm audit


    # - stage: Unit Tests
    #   script: npm run test

    # - stage: Build Application
    #   script:
    #     - docker build --tag app-nodejs .
